version: '3.9'
services:
  db:
    image: mysql:8.3.0
    container_name: mysql-govtech-db
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: govtech_assessment
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-setup:/docker-entrypoint-initdb.d
volumes:
  db_data:
